services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskboard-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=taskboard
      - DB_USER=postgres
      - DB_PASSWORD=example
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgis/postgis:13-3.3
    container_name: taskboard-db
    environment:
      - POSTGRES_DB=taskboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: